### ISSUE TITLE
The example link for data download fails for newer dates

### ISSUE THREAD

**Issue by ThomasRegier** [bundesAPI/smard-api#11]
The example link for data download fails for newer dates.
In the file bundesAPI/smard-api/ readme.md the following link is presented as an example:

'https://www.smard.de/app/chart_data/1223/DE/1223_DE_hour_1627855200000.json')

As I figured it out 1627855200000 stands for the start of day of the 1st of August 2021. 

It's possible to download data based on this link. 

If I try to get newer data. E.g. exactly one year later the resulting link fails: 

https://www.smard.de/app/chart_data/1223/DE/1223_DE_hour_1659391200000.json

How is it possible to download new data?

**Comment by nandbert2** [comment]
You first need to fetch the list of possible timestamps:

e.g. https://smard.api.proxy.bund.dev/app/chart_data/1223/DE/index_hour.json

You can use only one of the returned timestamps, not any epoch time.

e.g.: https://www.smard.de/app/chart_data/1223/DE/1223_DE_hour_1659304800000.json

**Comment by ThomasRegier** [comment]
Thank you
